<script setup lang="ts">
import { onMounted } from 'vue'
function createGrid (gridSize: number, cellSize: number) {
  const gridContainer = document.getElementById('grid-container')
  if (!gridContainer) return

  gridContainer.innerHTML = '' // Clear existing grid items

  // Update CSS variables
  document.documentElement.style.setProperty('--grid-size', gridSize.toString())
  document.documentElement.style.setProperty('--cell-size', `${cellSize}px`)

  // Create grid items
  for (let i = 0; i < gridSize * gridSize; i++) {
    const gridItem = document.createElement('div')
    gridItem.className = 'grid-item'
    gridContainer.appendChild(gridItem)
  }
}

// Example usage: create a 9x9 grid with cells of 50x50 pixels
createGrid(9, 50)

onMounted(() => {
  createGrid(9, 60)
})

</script>

<template>
  <div id="grid-container" class="grid-container">
        <!-- Grid items will be generated by JavaScript -->
  </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
