<script setup lang="ts">
import { onMounted } from 'vue'

interface GridContainer extends HTMLElement {
    style: CSSStyleDeclaration;
}

function createGrid (gridSize: number, cellSize: number): void {
  const gridContainer = document.getElementById('grid-container') as GridContainer
  if (!gridContainer) return
  gridContainer.innerHTML = '' // Clear existing grid items

  // Update CSS variables
  document.documentElement.style.setProperty('--grid-size', gridSize.toString())
  document.documentElement.style.setProperty('--cell-size', `${cellSize}px`)

  // Create grid items with hollow center
  for (let row = 0; row < gridSize; row++) {
    for (let col = 0; col < gridSize; col++) {
      // Determine if the cell is on the edge
      const isEdgeCell = row === 0 || row === gridSize - 1 || col === 0 || col === gridSize - 1

      const gridItem = document.createElement('div')
      gridItem.className = 'grid-item'
      if (!isEdgeCell) {
        gridItem.classList.add('hollow')
      }
      gridContainer.appendChild(gridItem)
    }
  }
}

onMounted(() => {
  createGrid(9, 50)
})

</script>

<template>
  <div id="grid-container" class="grid-container">
        <!-- Grid items will be generated by JavaScript -->
    </div>
</template>

<style scoped>
.logo {
  height: 6em;
  padding: 1.5em;
  will-change: filter;
}
.logo:hover {
  filter: drop-shadow(0 0 2em #646cffaa);
}
.logo.vue:hover {
  filter: drop-shadow(0 0 2em #42b883aa);
}
</style>
